# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('author', models.CharField(max_length=120, verbose_name='\u8457\u8005')),
                ('cover', models.CharField(max_length=500, verbose_name='\u753b\u50cf')),
                ('isbn', models.CharField(max_length=120, verbose_name='ISBN')),
                ('price', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5024\u6bb5')),
                ('publisher', models.CharField(max_length=120, verbose_name='\u51fa\u7248\u793e')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9\u753b\u50cf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookShelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookShelf', to='api.BookShelf', verbose_name='\u672c\u68da'),
        ),
    ]
